In [1]:
import pandas as pd
import random

In [2]:
# Activation function
def activation(net, threshold):
  if net >= threshold:
    return 1
  else:
    return -1

In [3]:
# Perceptron Training Algorithm

def perceptron(input_vector):

    # Initial setup
    threshold = random.randrange(0,5)
    w1 = random.randrange(-2,3)
    w2 = random.randrange(-2,3)
    wb = random.randrange(-2,3)
    print("Threshold = {0}\n".format(threshold))
    print("Initial weights:\nw1 = {0}\tw2 = {1}\twb = {2}\n".format(w1, w2, wb))

    # Algorithm
    repeat = True
    result = [0, 0, 0, 0]
    firstRunWts = ()
    j = 0
    while repeat:
        j += 1
        print("Iteration {0}".format(j))
        i = 0
        firstIteration = True
        for input in input_vector:
            x1, x2 = input
            t = target[i]
            net = x1*w1 + x2*w2 + wb
            y = activation(net, threshold)
            result[i] = y
            if y != t:
                w1 = w1 + (t-y) * x1
                w2 = w2 + (t-y) * x2
                wb = wb + (t-y)
            i += 1
            if firstIteration == True:
                firstRunWts = (w1, w2, wb)
            firstIteration = False
            print("Weights after input ({0}, {1}):\tw1 = {2}\tw2 = {3}\twb = {4}".format(x1, x2, w1, w2, wb))
        print("Iteration complete.")
        print("Updated weights:\nw1 = {0}\tw2 = {1}\twb = {2}\n".format(w1, w2, wb))
        lastRunWts = (w1, w2, wb)
        if lastRunWts == firstRunWts or result == target:
            repeat = False
    print("Final weights:\nw1 = {0}\tw2 = {1}\twb = {2}\n".format(w1, w2, wb))
    return result

In [4]:
def displayLogic(input_vector, target, result):
    column_names = pd.DataFrame([["Input Vector", "x1"],
                                ["Input Vector", "x2"],
                                ["Target", "Output"],
                                ["Predicted", "Output"]],
                                columns=["", ""])

    rows = []
    for i, input in enumerate(input_vector):
        x1, x2 = input
        row = []
        row.extend([x1, x2, target[i], result[i]])
        rows.append(row)

    columns = pd.MultiIndex.from_frame(column_names)

    df = pd.DataFrame(rows, columns=columns)
    df = df.style.set_properties(**{'text-align': 'right'})
    display(df)
    return

In [5]:
# AND Gate
x_1 = [-1, -1, 1, 1]
x_2 = [-1, 1, -1, 1]
input_vector = list(zip(x_1, x_2))
target = [-1, -1, -1, 1]

result = perceptron(input_vector)
displayLogic(input_vector, target, result)

Threshold = 0

Initial weights:
w1 = -2	w2 = 2	wb = -1

Iteration 1
Weights after input (-1, -1):	w1 = -2	w2 = 2	wb = -1
Weights after input (-1, 1):	w1 = 0	w2 = 0	wb = -3
Weights after input (1, -1):	w1 = 0	w2 = 0	wb = -3
Weights after input (1, 1):	w1 = 2	w2 = 2	wb = -1
Iteration complete.
Updated weights:
w1 = 2	w2 = 2	wb = -1

Iteration 2
Weights after input (-1, -1):	w1 = 2	w2 = 2	wb = -1
Weights after input (-1, 1):	w1 = 2	w2 = 2	wb = -1
Weights after input (1, -1):	w1 = 2	w2 = 2	wb = -1
Weights after input (1, 1):	w1 = 2	w2 = 2	wb = -1
Iteration complete.
Updated weights:
w1 = 2	w2 = 2	wb = -1

Final weights:
w1 = 2	w2 = 2	wb = -1

In [6]:
# OR Gate
x_1 = [-1, -1, 1, 1]
x_2 = [-1, 1, -1, 1]
input_vector = list(zip(x_1, x_2))
target = [-1, 1, 1, 1]

result = perceptron(input_vector)
displayLogic(input_vector, target, result)

Threshold = 3

Initial weights:
w1 = 1	w2 = 1	wb = -2

Iteration 1
Weights after input (-1, -1):	w1 = 1	w2 = 1	wb = -2
Weights after input (-1, 1):	w1 = -1	w2 = 3	wb = 0
Weights after input (1, -1):	w1 = 1	w2 = 1	wb = 2
Weights after input (1, 1):	w1 = 1	w2 = 1	wb = 2
Iteration complete.
Updated weights:
w1 = 1	w2 = 1	wb = 2

Iteration 2
Weights after input (-1, -1):	w1 = 1	w2 = 1	wb = 2
Weights after input (-1, 1):	w1 = -1	w2 = 3	wb = 4
Weights after input (1, -1):	w1 = 1	w2 = 1	wb = 6
Weights after input (1, 1):	w1 = 1	w2 = 1	wb = 6
Iteration complete.
Updated weights:
w1 = 1	w2 = 1	wb = 6

Iteration 3
Weights after input (-1, -1):	w1 = 3	w2 = 3	wb = 4
Weights after input (-1, 1):	w1 = 3	w2 = 3	wb = 4
Weights after input (1, -1):	w1 = 3	w2 = 3	wb = 4
Weights after input (1, 1):	w1 = 3	w2 = 3	wb = 4
Iteration complete.
Updated weights:
w1 = 3	w2 = 3	wb = 4

Final weights:
w1 = 3	w2 = 3	wb = 4

In [7]:
# NOR Gate
x_1 = [-1, -1, 1, 1]
x_2 = [-1, 1, -1, 1]
input_vector = list(zip(x_1, x_2))
target = [1, -1, -1, -1]

result = perceptron(input_vector)
displayLogic(input_vector, target, result)

Threshold = 2

Initial weights:
w1 = 1	w2 = 0	wb = 1

Iteration 1
Weights after input (-1, -1):	w1 = -1	w2 = -2	wb = 3
Weights after input (-1, 1):	w1 = 1	w2 = -4	wb = 1
Weights after input (1, -1):	w1 = -1	w2 = -2	wb = -1
Weights after input (1, 1):	w1 = -1	w2 = -2	wb = -1
Iteration complete.
Updated weights:
w1 = -1	w2 = -2	wb = -1

Iteration 2
Weights after input (-1, -1):	w1 = -1	w2 = -2	wb = -1
Weights after input (-1, 1):	w1 = -1	w2 = -2	wb = -1
Weights after input (1, -1):	w1 = -1	w2 = -2	wb = -1
Weights after input (1, 1):	w1 = -1	w2 = -2	wb = -1
Iteration complete.
Updated weights:
w1 = -1	w2 = -2	wb = -1

Final weights:
w1 = -1	w2 = -2	wb = -1

In [8]:
# NAND Gate
x_1 = [-1, -1, 1, 1]
x_2 = [-1, 1, -1, 1]
input_vector = list(zip(x_1, x_2))
target = [1, 1, 1, -1]

result = perceptron(input_vector)
displayLogic(input_vector, target, result)

Threshold = 3

Initial weights:
w1 = -1	w2 = 0	wb = 1

Iteration 1
Weights after input (-1, -1):	w1 = -3	w2 = -2	wb = 3
Weights after input (-1, 1):	w1 = -3	w2 = -2	wb = 3
Weights after input (1, -1):	w1 = -1	w2 = -4	wb = 5
Weights after input (1, 1):	w1 = -1	w2 = -4	wb = 5
Iteration complete.
Updated weights:
w1 = -1	w2 = -4	wb = 5

Iteration 2
Weights after input (-1, -1):	w1 = -1	w2 = -4	wb = 5
Weights after input (-1, 1):	w1 = -3	w2 = -2	wb = 7
Weights after input (1, -1):	w1 = -3	w2 = -2	wb = 7
Weights after input (1, 1):	w1 = -3	w2 = -2	wb = 7
Iteration complete.
Updated weights:
w1 = -3	w2 = -2	wb = 7

Iteration 3
Weights after input (-1, -1):	w1 = -3	w2 = -2	wb = 7
Weights after input (-1, 1):	w1 = -3	w2 = -2	wb = 7
Weights after input (1, -1):	w1 = -3	w2 = -2	wb = 7
Weights after input (1, 1):	w1 = -3	w2 = -2	wb = 7
Iteration complete.
Updated weights:
w1 = -3	w2 = -2	wb = 7

Final weights:
w1 = -3	w2 = -2	wb = 7